# Generated by Django 2.2.6 on 2019-10-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата заказа')),
                ('client_id', models.CharField(max_length=100, verbose_name='ID клиента')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес доставки')),
                ('dishes', models.ManyToManyField(to='app.Dish', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
