# Generated by Django 2.2.6 on 2019-10-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Выполнен'),
        ),
    ]
